# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('airbnb_id', models.IntegerField(unique=True)),
                ('airbnb_user_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('bedrooms', models.FloatField()),
                ('bathrooms', models.FloatField()),
                ('beds', models.FloatField()),
                ('property_type', models.CharField(max_length=255)),
                ('room_type_category', models.CharField(max_length=255)),
                ('square_feet', models.CharField(max_length=255)),
                ('person_capacity', models.IntegerField()),
                ('thumbnail_url', models.CharField(max_length=512)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('vacancy', models.BooleanField()),
                ('native_currency', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('weekend_price', models.FloatField()),
                ('weekly_price', models.FloatField()),
                ('monthly_price', models.FloatField()),
                ('price_for_extra_person', models.FloatField()),
                ('cleaning_fee', models.FloatField()),
                ('security_deposit', models.FloatField()),
                ('guests_included', models.IntegerField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='apartments.Apartment', unique_for_date='date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
